version: '3.8'

services:
  webapp:
    container_name: cleanarch_api
    build:
      context: .
      dockerfile: CleanArchitecture.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=10.1.34.134,1433;Database=ĐATN_Hieu;User Id=sa;Password=hieu@123;TrustServerCertificate=True;Encrypt=False;
